CREATE TABLE users
(
    id INT NOT NULL AUTO_INCREMENT,
    nip VARCHAR(255) UNIQUE,
    nama VARCHAR(255),
    kode_opd VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_users_kode_opd FOREIGN KEY (kode_opd) REFERENCES opd (kode_opd)
) ENGINE=InnoDB;