CREATE TABLE data_dan_informasi (
    id INT NOT NULL AUTO_INCREMENT,
    nama_data TEXT,
    sifat_data VARCHAR(255),
    jenis_data VARCHAR(255),
    produsen_data VARCHAR(255),
    pj_data VARCHAR(255),
    informasi_terkait_input VARCHAR(255),
    informasi_terkait_output VARCHAR(255),
    interoprabilitas VARCHAR(255),
    kode_opd varchar(255),
    tahun INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    rad_level_1_id INT,
    rad_level_2_id INT,
    rad_level_3_id INT,
    rad_level_4_id INT,
    strategic_id INT,
    tactical_id INT,
    operational_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_rad_level_1 FOREIGN KEY (rad_level_1_id) REFERENCES referensi_arsitekturs (id),
    CONSTRAINT fk_rad_level_2 FOREIGN KEY (rad_level_2_id) REFERENCES referensi_arsitekturs (id),
    CONSTRAINT fk_rad_level_3 FOREIGN KEY (rad_level_3_id) REFERENCES referensi_arsitekturs (id),
    CONSTRAINT fk_rad_level_4 FOREIGN KEY (rad_level_4_id) REFERENCES referensi_arsitekturs (id),
    CONSTRAINT fk_strategic_data FOREIGN KEY (strategic_id) REFERENCES pohon_kinerja (id),
    CONSTRAINT fk_tactical_data FOREIGN KEY (tactical_id) REFERENCES pohon_kinerja (id),
    CONSTRAINT fk_operational_data FOREIGN KEY (operational_id) REFERENCES pohon_kinerja (id),
    CONSTRAINT fk_kode_opd_data FOREIGN KEY (kode_opd) REFERENCES opd (kode_opd)
)ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;